### ISSUE TITLE
reach and combo counter registering hits that didnt deal damage

### ISSUE THREAD

**Issue by wyvest** [TGMDevelopment/simplehud-forge#10]
note: i have talked about this to tgm and I'm making this issue just for convenience

this happens because AttackEntityEvent is broken in 1.8.9 forge, it triggers hits that don't register due to mc's .5 second immunity.
this can be fixed by adding asm or add to net pipeline to check if the entity that is hit deals damage
however I don't know how to code asm yet

**Comment by MatthewTGM** [comment]
Thank you. This will hopefully be fixed in v1.7 or 8

**Comment by MatthewTGM** [comment]
Removed Combo Counter and this doesn't matter for reach display.
