### ISSUE TITLE
gui doesnt show up at all when using command

### ISSUE THREAD

**Issue by wyvest** [TGMDevelopment/simplehud-forge#7]
title
using forge 1.8.9 (using latest forge version) and only simplehud.

**Comment by MatthewTGM** [comment]
Are you using the command or the keybind?

**Comment by wyvest** [comment]
im using the command

**Comment by MatthewTGM** [comment]
Use the keybind. The command doesn't work at the moment

**Comment by wyvest** [comment]
ok :)

**Comment by MatthewTGM** [comment]
Fixed in v1.6
